pipeline {
    agent any
    stages {
        stage('Build') { 
            steps {
                withPythonEnv('python') {
                    sh 'pip install -r requirements.txt'
                }
            }
        }
    }
}