pipeline {
    agent {
        docker { image 'python:3.13.13-trixie' }
    } 
    stages {
        stage('Build') { 
            steps {
                sh 'python3 -m py_compile sources/add2vals.py sources/calc.py' 
            }
        }
    }
}